[package]
name = "ghost"
version = "0.1.0"
edition = "2021"

[dependencies]
demo = { path = "../demo", features = ["recorder"] }
game-interface = { path = "../game-interface" }

pool = { path = "../../lib/pool" }
